ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS street VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS ext_number VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS state VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR(15) NULL,
  ADD COLUMN IF NOT EXISTS country VARCHAR(80) NULL DEFAULT 'México',
  ADD COLUMN IF NOT EXISTS formatted_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS home_latitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS home_longitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS last_latitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS last_longitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS last_accuracy_meters DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS last_location_updated_at DATETIME NULL;

ALTER TABLE alertas_emergencia
  ADD COLUMN IF NOT EXISTS accuracy_meters DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS place_address VARCHAR(255) NULL;

ALTER TABLE incidentes
  ADD COLUMN IF NOT EXISTS latitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS longitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS accuracy_meters DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS place_address VARCHAR(255) NULL;
